export const ADD_SONGS = "ADD_SONGS";
export const REMOVE_SONGS = "REMOVE_SONGS";
export const ADD_SONGS_TO_SELECTION = "ADD_SONGS_TO_SELECTION";
export const REMOVE_SONGS_FROM_SELECTION = "REMOVE_SONGS_FROM_SELECTION";
