export const ADD_SONGS_TO_PLAYLIST = "ADD_SONGS_TO_PLAYLIST";
export const REMOVE_SONGS_FROM_PLAYLIST = "REMOVE_SONGS_FROM_PLAYLIST";
export const ADD_PLAYLIST = "ADD_PLAYLIST";
export const REMOVE_PLAYLIST = "REMOVE_PLAYLIST";
export const RENAME_PLAYLIST = "RENAME_PLAYLIST";
